With this change, bucketing/padding of input is applied to health check.
huggingface/tgi-gaudi pull request #245
Opened 2024-11-06 16:32 UTC by srajabos

# What does this PR do?

This PR applies bucketing/padding of input for proto messages in Causal LM 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@yuanwu2017 @mandy-li @tthakkal @skavulya

2024-11-07 03:29 UTC, yuanwu2017 commented on server/text_generation_server/models/causal_lm.py
> +        max_input_length: int = PAD_SEQUENCE_TO_MULTIPLE_OF,
max_input_length: Optional[int] = None,

2024-11-07 03:30 UTC, yuanwu2017 commented on server/text_generation_server/models/causal_lm.py
> -        max_input_length = max(r.data.truncate for r in requests)
if max_input_lenght == None:
   max_input_length = max(r.data.truncate for r in requests)

2024-11-07 03:31 UTC, yuanwu2017 requested changes
max_input_length

2024-11-07 17:06 UTC, srajabos commented
fixed with minimal changes to existing code.

2024-11-08 02:37 UTC, yuanwu2017 approved these changes

2024-11-08 17:41 UTC, skavulya commented
Thanks @srajabos  LGTM.

2024-11-08 17:42 UTC, skavulya approved these changes

2024-11-08 17:47 UTC, srajabos commented
@mandy-li @regisss , please review and merge if ok for you.

2024-11-08 19:06 UTC, mandy-li commented
@srajabos , pls address yuan's comments. if you already did, resolve the conversation

2024-11-08 20:03 UTC, srajabos commented
Sure @mandy-li. Resolved the conversation.

2024-11-08 20:28 UTC, tthakkal approved these changes

2024-11-08 23:04 UTC, schoi-habana approved these changes
lgtm

2024-11-11 03:35 UTC, srajabos commented
@tthakkal , @schoi-habana can you of you merge the changes. Thanks.

2024-11-18 21:38 UTC, regisss approved these changes

2024-11-18 21:38 UTC, merged