Remove nvidia packages
huggingface/tgi-gaudi pull request #247
Opened 2024-11-19 05:04 UTC by yuanwu2017

# What does this PR do?
Remove useless nvidia packages.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2024-11-21 16:56 UTC, mandy-li approved these changes

2024-11-21 17:03 UTC, tthakkal requested changes

2024-11-21 17:03 UTC, tthakkal commented on server/poetry.lock
@yuanwu2017 I agree we should remove nvidia packages, but I have few questions.
removing from peotry.lock doesn't mean we aren't installing right ?
how were we installing these packages? which package in our requirements require these installed?

2024-11-22 06:57 UTC, yuanwu2017 commented on server/poetry.lock
It only affects the command of  pip install and  make export-requirements

2024-11-22 06:58 UTC, yuanwu2017 commented on server/poetry.lock
It's also unclear to me whether they use make export-requirements.

2024-12-02 08:49 UTC, yuanwu2017 commented
@regisss  Please help to review.

2024-12-02 13:31 UTC, regisss commented on server/poetry.lock
These are dependencies of Torch. I guess Poetry listed them because Torch is a dependency of Optimum Habana: https://github.com/huggingface/optimum-habana/blob/4b4c8582b15cc499e0662484a5536c9827d649a0/setup.py#L34

The lock file doesn't do much in itself and is pretty big, I don't think we should care much about this kind of thing there. However, the `requirements.txt` file is generated from the lock file and that's where we have to be careful and to remove this kind of dependencies.

IMO it's faster and more straightforward to remove things directly in `requirements.txt`, so I wouldn't change anything in the lock file. But if that's a big deal to you to have these dependencies there, I'll merge this PR.

2024-12-02 17:10 UTC, mandy-li commented
@yuanwu2017 , Karol has identified dependent python package in requirements.txt which caused NV dependency in. Why do we still need this PR?

2024-12-03 00:52 UTC, closed without merging