Heap based router queue
huggingface/tgi-gaudi pull request #63
Opened 2024-02-22 07:52 UTC by mrs303

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2024-02-23 23:00 UTC, szutenberg approved these changes

2024-02-26 08:55 UTC, kdamaszk commented on router/src/queue.rs
> +    fn len(&self) -> usize {
new line

2024-02-26 08:56 UTC, kdamaszk commented on router/src/queue.rs
>  /// Queue State
new line

2024-02-26 08:56 UTC, kdamaszk commented on router/src/queue.rs
> +        while let Some(id_entry) = self.entries.pop() {
Why default implementation was wrong here? Less changes mean easier merge with upstream later.

2024-02-26 09:00 UTC, kdamaszk requested changes

2024-02-26 09:00 UTC, kdamaszk commented on router/src/queue.rs
> +        let threshold: u64 = match env::var("QUEUE_THREASHOLD_MS") {
typo

2024-02-26 09:00 UTC, kdamaszk commented on router/src/queue.rs
> +        let threshold: u64 = match env::var("QUEUE_THREASHOLD_MS") {
add flag to README

2024-02-26 09:53 UTC, kdamaszk approved these changes

2024-02-26 09:55 UTC, merged